# Site settings
name: Sam Thwaites
description: "Tech Entrepreneur"
url: "thwaitesy.com"

github_username:  thwaitesy
linkedin_username: thwaitesy
twitter_username: _thwaitesy
instagram_username: _thwaitesy

avatar_img_path: "img/avatar.jpg"
background_img_path: "img/1.jpg"

analytics:
  google: UA-41126415-1

# Build settings
markdown: kramdown
permalink: pretty
