# Site settings
name: Sam Thwaites
description: "Tech Entrepreneur"
url: "thwaitesy.com"

github_username:  thwaitesy
twitter_username: thwaitesynz
linkedin_username: samthwaites

avatar_img_path: "img/avatar.jpg"
background_img_path: "img/1.jpg"

analytics:
  google: UA-41126415-1

# Build settings
markdown: kramdown
permalink: pretty
